### ISSUE TITLE
video-constraints='{"facingMode":"environment"}' no longer works

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [PolymerElements/app-media#23]
I've updated `app-media` to the latest version and `video-constraints='{"facingMode":"environment"}'` no longer works.

**Comment by FluorescentHallucinogen** [comment]
This is my code:

```html
<app-media-devices
  kind="videoinput"
  selected-device="{{videoDevice}}">
</app-media-devices>

<app-media-stream
  video-device="[[videoDevice]]"
  video-constraints='{"facingMode":"environment"}'
  stream="{{stream}}"
  active>
</app-media-stream>
```

**Comment by FluorescentHallucinogen** [comment]
If I remove `video-device="[[videoDevice]]"` from `<app-media-stream>`, all is ok.

**Comment by cdata** [comment]
Yes, if you specify a device, the device will be given precedence. The device is intended to be a shortcut that adds an `exact` field to the video constraints referring to the `deviceId`.

**Comment by FluorescentHallucinogen** [comment]
One question: why the code above worked in previous versions? :)

**Comment by FluorescentHallucinogen** [comment]
For some reason, `video-constraints='{"facingMode":"environment"}'` no longer works again starting Chrome  for Android 61 (Dev and Canary). All is ok on Chrome for Android 60 and 59 (Beta and Stable).

Here is the code that I use:

```html
<app-media-stream
  video-constraints='{"facingMode":"environment"}'
  stream="{{stream}}"
  active>
</app-media-stream>
```

**Comment by FluorescentHallucinogen** [comment]
The problem is in https://github.com/webrtc/adapter.

**Comment by FluorescentHallucinogen** [comment]
See https://github.com/webrtc/adapter/issues/594.
