### ISSUE TITLE
app-media-recorder throws error when stream is null

### ISSUE THREAD

**Issue by JaySunSyn** [PolymerElements/app-media#46]
### Description
`app-media-stream` sets its `stream` property to null if `active` gets set to false.

`app-media-recorder` tries to re-compute the recorder property with a nullified stream. => throws error.
### Expected outcome
No error. 
### Actual outcome
```
Uncaught TypeError: Failed to construct 'MediaRecorder': parameter 1 is not of type 'MediaStream'.
```

### Steps to reproduce
Bind `stream` from `app-media-stream` to `app-media-recorder`.
Set `active` property  of `app-media-stream` to `false`.

**Comment by cdata** [comment]
Should be fixed by #47
